### ISSUE TITLE
wrap() method does not handle prototypes properly

### ISSUE THREAD

**Issue by XSven** [Ovid/sub-override#11]
perl 5.14.2
Sub::Override 0.10

I have to wrap the `File::Stat::stat($)` subroutine. When I do this I am getting the warning

`Prototype mismatch: sub File::stat::stat: none vs ($) at ../Sub-Override/lib/perl5/Sub/Override.pm line 112 during global destruction.`

I have changed

`+84 *$sub_to_replace = sub { $new_sub->( $self->{$sub_to_replace}, @_ ) };`

to

```
my $code =  sub { $new_sub->( $self->{$sub_to_replace}, @_ ) };
my $prototype = prototype($new_sub);
set_prototype($code, $prototype) if defined $prototype;
*$sub_to_replace = $code;
```

This change uses `Sub::Prototype::set_prototype()` and the perl built-in `prototype()` function.

If you are fine with this solution that introduces the addition dependency `Sub::Prototype` and that uses the perl built-in `prototype()` function I could create a PR.

**Comment by mvsjes2** [comment]
Ovid mentioned making me a collaborator to address this (I added the 'wrap' function recently). 

Thanks for the adjustment! That looks like the way to do it. I think we'd also need a way to restore the orignal prototype when we unwrap. Would you include some tests that check that?

**Comment by mvsjes2** [comment]
Thanks, just got your invite. :-)

**Comment by XSven** [comment]
I have created a PR #12 now
