### ISSUE TITLE
_ensure_code_slot_does_not_exist() doesn't use can() as a fallback

### ISSUE THREAD

**Issue by XSven** [Ovid/sub-override#20]
I am currently tuning a perl program reducing its startup time. One promising idea was to use lazy (`require` instead of `use` based) loading for some modules. After I have done that for one module, some test has failed. The problem was that a `Test2::Mock::override()` based mock has correctly complained about a non-existing symbol. `Sub::Override::replace()` would have done the same:

> This method will croak if the subroutine to be replaced does not exist.

I thought I need some other way to implement the lazy loading and I have started to play with `Module::Lazy`. I have compared `Sub::Override` with `Test::MockModule` and `Test2::Mock`

```
PERL_LAZYLOAD_DEBUG=1 perl -Ilib -MSub::Override -M'Module::Lazy qw(File::Spec)' -e'my $sub = Sub::Override->new("File::Spec::catfile" => sub {});'
Module::Lazy: request to load File::Spec (first time) at -e line 0.
Cannot replace non-existent sub (File::Spec::catfile) at -e line 1.
```
```
PERL_LAZYLOAD_DEBUG=1 perl -Ilib -MTest::MockModule -M'Module::Lazy qw(File::Spec)' -e'my $mock = Test::MockModule->new("File::Spec")->redefine(catfile => sub {});'
Module::Lazy: request to load File::Spec (first time) at -e line 0.
Module::Lazy: loading File::Spec from File/Spec.pm at .../Module-Lazy-deps/lib/perl5/Test/MockModule.pm line 90.
```
```
PERL_LAZYLOAD_DEBUG=1 perl -Ilib -MTest2::Mock -M'Module::Lazy qw(File::Spec)' -e'my $mock = Test2::Mock->new(class => "File::Spec", override => [ catfile => sub {} ]);'
Module::Lazy: request to load File::Spec (first time) at -e line 0.
Module::Lazy: loading File::Spec from File/Spec.pm at .../Module-Lazy-deps/lib/perl5/Test2/Mock.pm line 419.
```
I have detected a deficit or something that should at least be part of the caveats: `_ensure_code_slot_does_not_exist()` only inquires the symbol table to figure out if a symbol that should be mocked exists or not. Other mocking modules (`Test::MockModule` for example) are doing the same but they seem to have a `can()` based fallback. This fallback triggers some action in lazy loader modules like for example `Module::Lazy`.

**Comment by Ovid** [comment]
Are you using the latest version of `Sub::Override`? Quite a few things have been added. For example:

<h2 id="inherit" style="box-sizing: border-box; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: 700; line-height: 1.8em; color: rgb(51, 51, 51); margin-top: 21px; margin-bottom: 10.5px; font-size: 1.3em; scroll-margin-top: 60px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://metacpan.org/pod/Sub::Override#inherit" class="anchor" style="box-sizing: border-box; background-color: transparent; color: rgb(35, 82, 124); text-decoration: underline; scroll-margin-top: 60px; outline: 0px; padding-left: 9px; width: 26px; margin-left: -26px; vertical-align: top; font-size: 14px; display: inline-block;"><span class="fa fa-bookmark black" style="box-sizing: border-box; font-family: var(--fa-style-family, &quot;Font Awesome 6 Free&quot;); font-weight: var(--fa-style, 900); -webkit-font-smoothing: antialiased; display: var(--fa-display, inline-block); font-style: normal; font-variant: normal; text-rendering: auto; color: rgb(0, 0, 0); scroll-margin-top: 60px; visibility: visible;"></span></a>inherit</h2><pre style="box-sizing: border-box; overflow: auto; font-family: Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, Courier, &quot;Courier New&quot;, monospace; font-size: 14px; display: block; padding: 10px; margin: 0px 0px 10.5px; line-height: 1.42857; color: rgb(51, 51, 51); word-break: break-all; overflow-wrap: break-word; background-color: rgb(245, 245, 245); border: 1px solid rgb(204, 204, 204); border-radius: 4px; scroll-margin-top: 60px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="box-sizing: border-box; scroll-margin-top: 60px;"><div class="syntaxhighlighter nogutter  perl" style="box-sizing: border-box; scroll-margin-top: 60px; line-height: 1.2em; width: 968.8px;">
$sub->inherit($sub_name, $sub_body);
--


</div></div></pre><p style="box-sizing: border-box; margin: 0px 0px 10.5px; scroll-margin-top: 60px; font-size: 1.1em; color: rgb(51, 51, 51); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Checks that the subroutine exists in a parent class, but not in the current class, and injects it into the current class to inherit the parent's version.</p>

---

There's also an `inject` method which forces a subroutine into a namespace, but _only_ if it doesn't already exist.

<h2 id="inject" style="box-sizing: border-box; font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-weight: 700; line-height: 1.8em; color: rgb(51, 51, 51); margin-top: 21px; margin-bottom: 10.5px; font-size: 1.3em; scroll-margin-top: 60px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://metacpan.org/pod/Sub::Override#inject" class="anchor" style="box-sizing: border-box; background-color: transparent; color: rgb(35, 82, 124); text-decoration: underline; scroll-margin-top: 60px; outline: 0px; padding-left: 9px; width: 26px; margin-left: -26px; vertical-align: top; font-size: 14px; display: inline-block;"><span class="fa fa-bookmark black" style="box-sizing: border-box; font-family: var(--fa-style-family, &quot;Font Awesome 6 Free&quot;); font-weight: var(--fa-style, 900); -webkit-font-smoothing: antialiased; display: var(--fa-display, inline-block); font-style: normal; font-variant: normal; text-rendering: auto; color: rgb(0, 0, 0); scroll-margin-top: 60px; visibility: visible;"></span></a>inject</h2><pre style="box-sizing: border-box; overflow: auto; font-family: Menlo, Monaco, Consolas, &quot;Liberation Mono&quot;, &quot;Bitstream Vera Sans Mono&quot;, Courier, &quot;Courier New&quot;, monospace; font-size: 14px; display: block; padding: 10px; margin: 0px 0px 10.5px; line-height: 1.42857; color: rgb(51, 51, 51); word-break: break-all; overflow-wrap: break-word; background-color: rgb(245, 245, 245); border: 1px solid rgb(204, 204, 204); border-radius: 4px; scroll-margin-top: 60px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div style="box-sizing: border-box; scroll-margin-top: 60px;"><div class="syntaxhighlighter nogutter  perl" style="box-sizing: border-box; scroll-margin-top: 60px; line-height: 1.2em; width: 968.8px;">
$sub->inject($sub_name, $sub_body);
--


</div></div></pre>

**Comment by XSven** [comment]
I am using the most recent 0.12 version. Using `inherit()` helps

```
PERL_LAZYLOAD_DEBUG=1 perl -Ilib -MSub::Override -M'Module::Lazy qw(File::Spec)' -e'my $sub = Sub::Override->new->inherit("File::Spec::catfile" => sub {});'
Module::Lazy: request to load File::Spec (first time) at -e line 0.
Module::Lazy: loading File::Spec from File/Spec.pm at /home/micsw/perl-5.22.3/Module-Lazy-deps/lib/perl5/Sub/Override.pm line 174.
```

although I still have the feeling that some additional documentation is missing.
