### ISSUE TITLE
Sub gets lost when you overwrite a Sub::Override object with a new Sub::Override object in lexical scope

### ISSUE THREAD

**Issue by simbabque** [Ovid/sub-override#5]
When working with Sub::Override I had a bug that originally was hard to spot. Essentially, I did this:

```
use strict;
use warnings 'all';
use feature 'say';
use Sub::Override;

sub bar {
    'original';
}

say '1 ' . bar(); # original
my $sub = Sub::Override->new( 'bar' => sub {'first'} );
say '2 ' . bar(); # first

$sub = Sub::Override->new( 'bar' => sub {'second'} );
say '3 ' . bar(); # original
```

The output will be as follows.

```
1 original
2 first
3 original
```

On the first glance it looks like there is something not working, because the `new` call with _second_ doesn't seem to work. The _3_ output should say _second_. But that is not the case. 

What's happening here I believe is that a new Sub::Override object gets created, overriding `bar` with _second_. Then it gets assigned to `$sub`, at which point the old object gets its `DESTROY` called. That will restore all overrides and `bar` gets restored. So `bar`, which was overridden with _first_ and then got overridden with _second_, will now be reset and is _original_ again. `$sub` contains the second Sub::Override object, but the sub is not overridden any more. That's weird, but it makes sense.

However, if you put all of that into a block to make it lexical and call `bar` outside the block again, it gets weird.

```
use strict;
use warnings 'all';
use feature 'say';
use Sub::Override;

sub bar {
    'original';
}

say '1 ' . bar(); # original
{
    my $sub = Sub::Override->new( 'bar' => sub {'first'} );
    say '2 ' . bar(); # first

    $sub = Sub::Override->new( 'bar' => sub {'second'} );
    say '3 ' . bar(); # original
}
say '4 ' . bar(); # first
```

This says

```
1 original
2 first
3 original
4 first
```

What's going on now? The call at _4_ should say _original_, but it says _first_. It looks like the original sub has gotten lost on the way, but I'm not sure why.

I suggest to put a CAVEAT section into the POD to warn users not to do what I did in the first example, because it's wrong and very good to shoot oneself in the foot.

Regarding the second one, I will dig more and update here if I figure out why this is happening.

**Comment by simbabque** [comment]
I dug a bit deeper. Here is what I found.

```perl
use strict;
use warnings 'all';
use feature 'say';
use Sub::Override;
use Class::Method::Modifiers;
use Data::Printer deparse => 1;
use B::Deparse;

around 'Sub::Override::DESTROY' => sub {
    my $orig = shift;
    my $self = shift;

    say 'DESTROYING Sub::Override object. Restoring &bar to:';
    say np $self->{'main::bar'};
    $self->$orig(@_);
    say '&bar is now:';
    say B::Deparse->new( "-p", "-sC" )->coderef2text( \&bar );
};

around 'Sub::Override::new' => sub {
    my $orig = shift;
    my $self = shift;

    say "Creaing new Sub::Override with args:";
    say np @_;
    my $return = $self->$orig(@_);

    say "Created this object:";
    say np $return;
    return $return;
};

sub bar {
    'original';
}

say '1 ' . bar();    # original
{
    say 'replacing with first ...';
    my $sub = Sub::Override->new( 'bar' => sub {'first'} );
    say '2 ' . bar();    # first

    say 'replacing with second ...';
    $sub = Sub::Override->new( 'bar' => sub {'second'} );

    say '$sub now stores this sub:';
    say np $sub->{'main::bar'};
    say '3 ' . bar();    # original
}
say '4 ' . bar();        # first

```

This checks which function is in `&bar` and which one is stored away as the original inside the Sub::Override object.

```
1 original
replacing with first ...
Creaing new Sub::Override with args:
[
    [0] "bar",
    [1] sub {
            use warnings;
            use strict;
            use feature 'say';
            'first';
        }
]
Created this object:
Sub::Override  {
    public methods (4) : DESTROY, new, replace, restore
    private methods (0)
    internals: {
        main::bar   sub {
                use warnings;
                use strict;
                use feature 'say';
                'original';
            }
    }
}
2 first
replacing with second ...
Creaing new Sub::Override with args:
[
    [0] "bar",
    [1] sub {
            use warnings;
            use strict;
            use feature 'say';
            'second';
        }
]
Created this object:
Sub::Override  {
    public methods (4) : DESTROY, new, replace, restore
    private methods (0)
    internals: {
        main::bar   sub {
                use warnings;
                use strict;
                use feature 'say';
                'first';
            }
    }
}
DESTROYING Sub::Override object. Restoring &bar to:
\ sub {
        use warnings;
        use strict;
        use feature 'say';
        'original';
    }
&bar is now:
{
    use warnings;
    use strict;
    use feature 'say';
    'original';
}
$sub now stores this sub:
\ sub {
        use warnings;
        use strict;
        use feature 'say';
        'first';
    }
3 original
DESTROYING Sub::Override object. Restoring &bar to:
\ sub {
        use warnings;
        use strict;
        use feature 'say';
        'first';
    }
&bar is now:
{
    use warnings;
    use strict;
    use feature 'say';
    'first';
}
4 first
```

From this rather messy output we can see that what it does seems to be:

- create a new object
- replace _original_ with _first_
- store _original_ in the object
- assign that object to `$sub`
- create a second object
- replace _first_ with _second_
- store _first_ in the new object
- destroy the first object, which replaces `&bar` with _original_
- assign the second object to the scoped variable `$sub`; nothing gets replaced any more at this point, and `&bar` is still _original_
- at this point _second_ is lost
- when `$sub` goes out of scope, destroy the second object, which restores `&bar` to _first_ because that's what's saved in the second object
- at this point _original_ is lost

I am still not sure what to do with this knowledge. I think this is not a bug in Sub::Override, but rather a flawed way of using it. I do think we should warn users about it though.

**Comment by ichesnokov** [comment]
It's worth to mention in the documentation that `Sub::Override` is designed to be a singleton - or at least warn the users against trying to create several instances of it to mock the same sub.
